### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by jmutnick** [flavio-fernandes/mqtt2kasa#1]
Getting this error.  Any suggesstions?

(env) pi@home-assistant-pi4:~/sh/kasa/mqtt2kasa $ python3 mqtt2kasa/main.py ./data/config.yaml
Traceback (most recent call last):
  File "mqtt2kasa/main.py", line 12, in <module>
    from mqtt2kasa.keep_alive import (
  File "/home/pi/sh/kasa/mqtt2kasa/mqtt2kasa/keep_alive.py", line 76, in <module>
    kasas: dict[str, Kasa], kas: dict[str, KeepAlive], mqtt_send_q: asyncio.Queue
TypeError: 'type' object is not subscriptable

**Comment by jmutnick** [comment]
These are version of the components installed:

Successfully installed anyio-2.2.0 asyncclick-7.1.2.3 asyncio-mqtt-0.8.1 asyncio-throttle-1.0.2 idna-3.1 importlib-metadata-3.10.0 paho-mqtt-1.5.1 python-kasa-0.4.0.dev2 pyyaml-5.4.1 sniffio-1.2.0 typing-extensions-3.7.4.3 zipp-3.4.1

**Comment by flavio-fernandes** [comment]
hmm....

Can you try using a newer python 3 version? I use 3.9, but something newer
than 3.7 should be ok.

-- flaviof

**Comment by jmutnick** [comment]
Upgraded to 3.9.4 and it is working now.  Thanks!
