### ISSUE TITLE
emeter output is not usable

### ISSUE THREAD

**Issue by gck303** [flavio-fernandes/mqtt2kasa#10]
I have tried to use the emeter output, but it has a couple of issues:
- it is surrounded by <>
- all the different parameters are within a single payload

I have edited the code to remove the <> send multiple messages. Can this be incorporated in the standard code?

`async def handle_emeter_event_kasa(
    kasa_emeter: KasaEmeterEvent, run_state: RunState, mqtt_send_q: asyncio.Queue
):
    kasa = run_state.kasas.get(kasa_emeter.name)
    if not kasa:
        logger.warning(
            f"Unable to find device with name {kasa_emeter.name}. Ignoring kasa emeter event"
        )
        return
    topic = f"{kasa.topic}/emeter"
    payload = kasa_emeter.emeter_status
    payload = payload.replace('<', '')
    payload = payload.replace('>', '')
    logger.info(
        f"Kasa emeter event requesting mqtt for {kasa_emeter.name} to publish"
        f" {topic} as {payload}"
    )
    await mqtt_send_q.put(MqttMsgEvent(topic=topic, payload=payload))

    myList = payload.split()
    print(myList)

    for item in myList:
        print( item )
        topic = f"{kasa.topic}/emeter/" + item.split('=')[0]
        print( 'topic =' + topic)
        payload =  item.partition("=")[2]
        await mqtt_send_q.put(MqttMsgEvent(topic=topic, payload=payload))
`

**Comment by flavio-fernandes** [comment]
> I have tried to use the emeter output, but it has a couple of issues:
> 
>     * it is surrounded by <>
> 
>     * all the different parameters are within a single payload
> 
> 
> I have edited the code to remove the <> send multiple messages. Can this be incorporated in the standard code?

Of course, @gck303 ! ~~Do you want to make a pull request? Otherwise, I will make these changes for you in the near future.~~

Pushing changes soon. :)
