### ISSUE TITLE
ValueError: git history requires a target version of pbr.version.SemanticVersion(0.0.3), but target version is pbr.version.SemanticVersion(0.0.1)

### ISSUE THREAD

**Issue by sirkingchase** [flavio-fernandes/mqtt2kasa#14]
When running the install command ex: _sudo python3 setup.py install_

The following SemanticVersion exception will be thrown:
_ValueError: git history requires a target version of pbr.version.SemanticVersion(0.0.3), but target version is pbr.version.SemanticVersion(0.0.1)_

I fixed this by updating version in the file: setup.cfg to 0.0.3

**Comment by flavio-fernandes** [comment]
> When running the install command ex: _sudo python3 setup.py install_
> 
> The following SemanticVersion exception will be thrown: _ValueError: git history requires a target version of pbr.version.SemanticVersion(0.0.3), but target version is pbr.version.SemanticVersion(0.0.1)_
> 
> I fixed this by updating version in the file: setup.cfg to 0.0.3

Awesome! Can you please make a PR, @sirkingchase ? Otherwise, I will take a look at it when I find time.
