### ISSUE TITLE
Question: brightness support

### ISSUE THREAD

**Issue by aderesh** [flavio-fernandes/mqtt2kasa#18]
Hi

Before anything, thanks for library/module!

My understanding, this library/module uses 'kasa-python' internally which supports setting brightness "kasa --host 192.168.0.15 brightness 50". Does the library/module support setting brightness via mqtt? If not, any tips how to add the support (files to update, commands etc)?

Thanks!

**Comment by flavio-fernandes** [comment]
Hi @aderesh ! You are right, I can see now in the library that there is an `hsv` attribute:

Ref: https://python-kasa.readthedocs.io/en/latest/smartbulb.html

I think that can be integrated into mqtt2kasa  for sure. I am currently out of cycles for doing that, but would love to play with it in the future.

As for implementing this, I would start by looking at the file https://github.com/flavio-fernandes/mqtt2kasa/blob/main/mqtt2kasa/kasa_wrapper.py and then "pull the trhead" on the ramifications for handling it. I have some good test coverage to make sure nothing regresses, so I would make sure to add some test cases for exercising the hsv there too. Hope this helps and thank you for creating this issue.

**Comment by aderesh** [comment]
thanks @flavio-fernandes. I was looking at `brightness` property instead of `hsv` since I'm targeting hs220 - https://github.com/python-kasa/python-kasa/blob/7d4dc4c710d08d415ddb70cae4a7206784a66222/kasa/iot/iotdimmer.py#L108. Currently, I've updated the code to report `brightness` changes via mqtt but I'm not quite sure what would be the best topic for that.
If I understand it correctly, `locations/topic` and `globals/topic_format` control our state (e.g. `on`/`off`) only. Do you have any ideas/preferences how we should handle `brightness`, `hsv` and any other attributes in terms of topics? 
We can send `brightness=100` in the same `topic` - this is what I currently use in my branch.
Or, we could introduce something like `locations/brightness_topic` with `globals/brightness_topic_format`, similarly to what we currently have. 
Other options I can think of would probably introduce breaking changes and I'm not sure if it's desirable. 

Side note, MQTT and python are new topics to me :)

Thanks!

**Comment by aderesh** [comment]
I've just found https://github.com/flavio-fernandes/mqtt2kasa/issues/10 reference in the code. to be consistent, I'll use a separate "/brightness" topic for now. Still, would be curious to know you opinion

**Comment by flavio-fernandes** [comment]
> I've just found #10 reference in the code. to be consistent, I'll use a separate "/brightness" topic for now. Still, would be curious to know you opinion

ah. nice! then we should add a `f"{kasa.topic}/brightness`

reference in the code:  https://github.com/flavio-fernandes/mqtt2kasa/blob/a2f09c37f78f1eb3544b4a7b8c5006c3fb12f0ac/mqtt2kasa/main.py#L63

The emeter is just on a publish, so we will need a little extra to make the code subscribe to that specific topic too. 

For that, take a look at:  https://github.com/flavio-fernandes/mqtt2kasa/blob/a2f09c37f78f1eb3544b4a7b8c5006c3fb12f0ac/mqtt2kasa/main.py#L192-L202

We will need to add a check to see if device supports brightness and then keep a subscribe for the ones that do.

Take a look here: https://github.com/flavio-fernandes/mqtt2kasa/blob/a2f09c37f78f1eb3544b4a7b8c5006c3fb12f0ac/mqtt2kasa/main.py#L192-L202 

In the class Kasa class (https://github.com/flavio-fernandes/mqtt2kasa/blob/a2f09c37f78f1eb3544b4a7b8c5006c3fb12f0ac/mqtt2kasa/kasa_wrapper.py#L17) add a `self.topic_brightness`.

See what you think and let me know if that is enough to get you going.

Have fun! :)

**Comment by aderesh** [comment]
thanks @flavio-fernandes for quick replies. I created PR before noticing your previous message :( - https://github.com/flavio-fernandes/mqtt2kasa/pull/19. Please check if it looks good and let me know if you still want `self.topic_brightness`. I think the rest should be similar to what you've described.

**Comment by flavio-fernandes** [comment]
Fixed in 0857455edd8f00803b4c4501f67c4242e4f52fa6 by @aderesh
