### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by honkbonk** [flavio-fernandes/mqtt2kasa#2]
When running as documented I see the following error...

Traceback (most recent call last):
  File "mqtt2kasa/main.py", line 12, in <module>
    from mqtt2kasa.keep_alive import (
  File "/home/pi/kasa/mqtt2kasa/mqtt2kasa/keep_alive.py", line 76, in <module>
    kasas: dict[str, Kasa], kas: dict[str, KeepAlive], mqtt_send_q: asyncio.Queue
TypeError: 'type' object is not subscriptable

My configuration looks like this...

---

knobs:
    # Note: normally you don't set these... here just to show how to
    # devel and debug
    # log_to_console: false
    # log_level_debug: false
mqtt:
    # ip/dns for the mqtt broker
    host: 192.168.35.90
globals:
    # every location will be managed using a unique mqtt topic
    # unless explicitly specified, this format will be used
    topic_format: /{}/switch
    # kasa will monitor the current state of the device every
    # poll interval, in seconds. You can override on a per device
    poll_interval: 11
locations:
    # coffee maker. To turn it on, use mqtt publish
    # topic: /coffee_maker/switch payload: on
    # subscribe to /coffee_maker/switch to know its state
    living_room_lights
        host: 192.168.35.103
    desk_lights:
        host: 192.168.35.120

Any help would be appreciated.

**Comment by flavio-fernandes** [comment]
Hi,

I suspect you are having the same issue as in
https://github.com/flavio-fernandes/mqtt2kasa/issues/1

As documented in readme file:
**NOTE:** Use python 3.7 or newer, as this project requires a somewhat
recent implementation of [asyncio](https://realpython.com/async-io-python/).

Maybe we should make that a little more visible, what do you think?

**Comment by honkbonk** [comment]
> Hi,
> 
> I suspect you are having the same issue as in
> #1
> 
> As documented in readme file:
> **NOTE:** Use python 3.7 or newer, as this project requires a somewhat
> recent implementation of [asyncio](https://realpython.com/async-io-python/).
> 
> Maybe we should make that a little more visible, what do you think?

I'm using Python 3.7.3 so maybe it's more about the version of asyncio.  

I'll dig deeper there and see.

**Comment by williamp0044** [comment]
> > Hi,
> > I suspect you are having the same issue as in
> > #1
> > As documented in readme file:
> > **NOTE:** Use python 3.7 or newer, as this project requires a somewhat
> > recent implementation of [asyncio](https://realpython.com/async-io-python/).
> > Maybe we should make that a little more visible, what do you think?
> 
> I'm using Python 3.7.3 so maybe it's more about the version of asyncio.
> 
> I'll dig deeper there and see.

Hi! Did you make any progress? Having the same issue. On the same python version.

**Comment by flavio-fernandes** [comment]
Sorry to hear. I use 3.9 and was not aware that anything lower than that is not working. Please consider using 3.9 or see if 3.8 is also good? I should update that readme as soon as we find out.

**Comment by flavio-fernandes** [comment]
> > > Hi,
> > > I suspect you are having the same issue as in
> > > #1
> > > As documented in readme file:
> > > **NOTE:** Use python 3.7 or newer, as this project requires a somewhat
> > > recent implementation of [asyncio](https://realpython.com/async-io-python/).
> > > Maybe we should make that a little more visible, what do you think?
> > 
> > 
> > I'm using Python 3.7.3 so maybe it's more about the version of asyncio.
> > I'll dig deeper there and see.
> 
> Hi! Did you make any progress? Having the same issue. On the same python version.

Can you try a small change and see your python version works better? Basically, simply rewrite the trouble line:
https://github.com/flavio-fernandes/mqtt2kasa/blob/1c6f8c4d8581e3b1aa78410afab3ebd9bf9f3a62/mqtt2kasa/keep_alive.py#L76
as
```
kasas, kas, mqtt_send_q
```
