### ISSUE TITLE
MQTT publishing retain flag after polling

### ISSUE THREAD

**Issue by iointerrupt** [flavio-fernandes/mqtt2kasa#7]
Currently the publish handler uses the default retain payload flag of the mqtt library which is "false".  This should be configurable either globally or per device.

I retain payloads for all my kasa switches when publishing to the topic.  However, if I directly turn the device on or off from the switch, when mqtt2kasa polls the devices it will see the changed state and publish to the topic with ```retain = false```.

Since I retain for all devices, I manually modified mqtt.py to publish with ```retain = true``` as a workaround. Additionally the ```qos``` value could be configurable the same way.

**Comment by flavio-fernandes** [comment]
Please take a look at https://github.com/flavio-fernandes/mqtt2kasa/commit/9269fba62be65a6f68ff336646c9e9057a4ba7dc , @iointerrupt
And thank you for opening the issue.

**Comment by iointerrupt** [comment]
Well that was fast.  This is great.  Although I am wondering whether retention should be per topic (location): use the default specified under [mqtt] if not specified under each [location].

Anyway, don't need to overcomplicate the issue however. Thanks for your continued support.  Been using it for about 2 years and its been working flawless for my home automation with 20+ kasa switches.

**Comment by flavio-fernandes** [comment]
> Well that was fast. This is great. Although I am wondering whether retention should be per topic (location): use the default specified under [mqtt] if not specified under each [location].
> 
> Anyway, don't need to overcomplicate the issue however. Thanks for your continued support. Been using it for about 2 years and its been working flawless for my home automation with 20+ kasa switches.

ha, no problem; it was an easy ask. 
I will defer doing that setting on a per location until the need arises. less places for a bug to live. ;)

glad to hear you are using it it and that is has worked well for your needs.

best,

-- flaviof
