### ISSUE TITLE
Exception: Invalid files: /run/systemd/journal/syslog, /var/run/syslog, /device/log

### ISSUE THREAD

**Issue by gck303** [flavio-fernandes/mqtt2kasa#8]
I am installing it on a Ubuntu server (Ubuntu 22.04.2 LTS). 

During the first install I got the same error as : https://github.com/flavio-fernandes/mqtt2kasa/issues/5

Second install I get an exception raised due to invalid files. Not sure what is gong on, but I think that there is a problem somewhere. 

`(env) gck@emonpi:~/mqtt2kasa$ python3 mqtt2kasa/main.py ./data/config.yaml
Traceback (most recent call last):
  File "/home/gck/mqtt2kasa/mqtt2kasa/main.py", line 263, in <module>
    log.initLogger()
  File "/home/gck/mqtt2kasa/mqtt2kasa/log.py", line 28, in initLogger
    logHandlerAddress = _log_handler_address(
  File "/home/gck/mqtt2kasa/mqtt2kasa/log.py", line 16, in _log_handler_address
    raise Exception("Invalid files: %s" % ", ".join(files))
Exception: Invalid files: /run/systemd/journal/syslog, /var/run/syslog, /device/log
(env) gck@emonpi:~/mqtt2kasa$
`

**Comment by flavio-fernandes** [comment]
Update: I'm trying to bring up a VM with Ubuntu 22.04. Once I manage to do that, I will change that logic to make sure it works.

**Comment by gck303** [comment]
Thank you!!!

**Comment by flavio-fernandes** [comment]
@gck303 could you please give me more details about how you installed your Ubuntu Server?

I have installed Ubuntu 22.04 and see no issues finding the syslog file (below).

We need to understand why/how your system does not have the file `/run/systemd/journal/syslog` .


```
(env) vagrant@kasavm:~$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
(env) vagrant@kasavm:~$ for f in "/run/systemd/journal/syslog" "/var/run/syslog" "/device/log" ; do [ -e "$f" ] && echo found $f ; done
found /run/systemd/journal/syslog
(env) vagrant@kasavm:~$
```

**Comment by gck303** [comment]
Thank you so much for looking. How very strange. It does not have one of those!

`(env) gck@emonpi:/run/systemd/journal$ sudo ls
dev-log  flushed  io.systemd.journal  kernel-seqnum  socket  stdout  streams
`

It is a ubuntu server that I use for all sorts of misc. things. It runs as a VM. 

The system was installed in March 2022 (found via ls -lt /var/log/installer), so it is likely that I have upgraded it to 22.04 at some point .
