### ISSUE TITLE
Multiple and alternating messages. 

### ISSUE THREAD

**Issue by gck303** [flavio-fernandes/mqtt2kasa#9]
I am getting strange repeated messages which are alternating on/off. Not quite sure what is going on. 

This is the output from whening running the script in the foreground. 

Any ideas? 

When I restart the script the problem goes. 

`Device dehumidifier is too busy to take request to be set as on
Device dehumidifier is too busy to take request to be set as off
Device dehumidifier is too busy to take request to be set as on
Device dehumidifier is too busy to take request to be set as off
Device dehumidifier is too busy to take request to be set as on
Device dehumidifier is too busy to take request to be set as off
Device dehumidifier is too busy to take request to be set as on
Device dehumidifier is too busy to take request to be set as off
Device dehumidifier is too busy to take request to be set as on
Device dehumidifier is too busy to take request to be set as off
Device dehumidifier is too busy to take request to be set as on
Device dehumidifier is too busy to take request to be set as off
Device dehumidifier is too busy to take request to be set as on
Device dehumidifier is too busy to take request to be set as off
Device dehumidifier is too busy to take request to be set as on
Device dehumidifier is too busy to take request to be set as off
Device dehumidifier is too busy to take request to be set as on
Device dehumidifier is too busy to take request to be set as off
Device dehumidifier is too busy to take request to be set as on
Device dehumidifier is too busy to take request to be set as off
Device dehumidifier is too busy to take request to be set as on
Device dehumidifier is too busy to take request to be set as off
Device dehumidifier is too busy to take request to be set as on
`

**Comment by flavio-fernandes** [comment]
This means that the kasa device is being asked to change state too often and the code is explicitly throttling it.

https://github.com/flavio-fernandes/mqtt2kasa/blob/17096b010773433ba80c5bdc2e63fdc11d0bf858/mqtt2kasa/main.py#L104-L109

Any chance that is happening in your environment?

The queue size is 4:

https://github.com/flavio-fernandes/mqtt2kasa/blob/17096b010773433ba80c5bdc2e63fdc11d0bf858/mqtt2kasa/kasa_wrapper.py#L30

Which means, the Kasa device may be getting bombarded with requests and that seems suspicious.

Not a bug; functioning as implemented. :)
